// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_6JSBy29xDyiWPoEnD-VQamUbbcWmODg',
    appId: '1:850125479678:web:c698433094dade1a6c0faf',
    messagingSenderId: '850125479678',
    projectId: 'mental-state-archery',
    authDomain: 'mental-state-archery.firebaseapp.com',
    storageBucket: 'mental-state-archery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofadgkFZmXfJUM3UIZJ5xuPnSEeb-E1s',
    appId: '1:850125479678:android:0986859c83d65c6e6c0faf',
    messagingSenderId: '850125479678',
    projectId: 'mental-state-archery',
    storageBucket: 'mental-state-archery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-VPgcTfteZTWfeyjqyXpNGOhoY5AJ5M',
    appId: '1:850125479678:ios:4f266e135c372e726c0faf',
    messagingSenderId: '850125479678',
    projectId: 'mental-state-archery',
    storageBucket: 'mental-state-archery.firebasestorage.app',
    iosBundleId: 'com.example.archery2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-VPgcTfteZTWfeyjqyXpNGOhoY5AJ5M',
    appId: '1:850125479678:ios:4f266e135c372e726c0faf',
    messagingSenderId: '850125479678',
    projectId: 'mental-state-archery',
    storageBucket: 'mental-state-archery.firebasestorage.app',
    iosBundleId: 'com.example.archery2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_6JSBy29xDyiWPoEnD-VQamUbbcWmODg',
    appId: '1:850125479678:web:c8821f7e9e4b3d7a6c0faf',
    messagingSenderId: '850125479678',
    projectId: 'mental-state-archery',
    authDomain: 'mental-state-archery.firebaseapp.com',
    storageBucket: 'mental-state-archery.firebasestorage.app',
  );
}
